
@startsalt  upload_arquivo_laudo
<style>
saltDiagram {
  BackgroundColor #f6f6f5
}
</style>
skinparam dpi 100
title Marcar perícia como validada
header MPMG
caption Sistema de Perícia MPMG
{
            {^**Laudo N°** <color:blue>**2323-25**
            **Descrição**: consectetur adipiscing elit, sed do eiusmod
            .
            **Tema**: Lorem ipsum dolor sit amet | **Status**: eiusmod tempor
            .
            **Data de Cadastro**: 01/04/2025 | <color:red>**Data limite**: 02/05/2025
            .
            **Localização**: consectetur - adipiscing - el. |  **Última alteração**: 28/03/2025 20:35
            .
            .
            {^ **Peritos**
                35435345 - Lorem ipsum dolor sit amet
                3332232  - Lorem ipsum dolor sit amet
            }
            | {^ **Ocorrência:** dd/mm/yyyy}
            .
            {^ **Denunciado:**
                ***Nome**  | adipiscing elit, sed do eiusmod
                ***CPF**   | 999.999.999-99
                **Observações**   | adipiscing elit, sed do eiusmod
                . | adipiscing elit, sed do eiusmod
                . | adipiscing elit, sed do eiusmod
                .
            }

        }
        .
        Confirma alteração do status para **Validada?** [x]
            .

    .
    {[Salvar] | [Cancelar]}
.
}
@endsalt
