@startsalt
<style>
saltDiagram {
  BackgroundColor #f6f6f5
}
</style>
skinparam dpi 100
title Grid de Temas
header MPMG
caption Sistema de Perícia MPMG
{
    [Novo Tema]
    {#
    **ID** | **Tema**     | **Status** | **Questionário**                     |**Ações**
    00120 | Lorem ipsum   | Ativo      | adipiscing elit, sed do eiusmod      | { [Editar] | [Excluir] }
    00120 | Lorem ipsum   | Ativo      | adipiscing elit, sed do eiusmod      | { [Editar] | [Excluir] }
    00120 | Lorem ipsum   | Ativo      | adipiscing elit, sed do eiusmod      | { [Editar] | [Excluir] }
    00120 | Lorem ipsum   | Ativo      | adipiscing elit, sed do eiusmod      | { [Editar] | [Excluir] }
    }
    .
    .
}
@endsalt